# File: service-mesh-gitops/argocd-applications/service-mesh-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-ocp1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Control sync order
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: default
  source:
    repoURL: https://github.com/ed-kyndryl/service-mesh.git
    targetRevision: main
    path: charts/service-mesh
    helm:
      valueFiles:
        - ../../cluster-configs/ocp1/service-mesh-values.yaml  
  destination:
    server: https://api.ocp1.edskii.online:6443
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true