# ServiceMeshMemberRoll
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: {{ .Values.meshNamespace }}
spec:
  members:
    # List your application namespaces here
    - test