# ServiceMeshControlPlane
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.meshName }}
  namespace: {{ .Values.meshNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  version: v2.6 # Create parameter for it in Helm
  tracing:
    type: None
    sampling: 10000
  addons:
    kiali:
      enabled: true
    grafana:
      enabled: true